### ISSUE TITLE
Datatype of timezone is float

### ISSUE THREAD

**Issue by yaliniyalu** [ker0x/messenger#104]
In UserResponse class the datatype of timezone is int. But I get my timezone as 5.5 (+5:30). So the datatype of timezone may be float. I got error as

PHP Fatal error:  Uncaught TypeError: Return value of Kerox\Messenger\Response\UserResponse::getTimezone() must be of the type integer or null, float returned in /vendor/kerox/messenger/src/Response/UserResponse.php:105

**Comment by ker0x** [comment]
I close this issue as i just released  v2.1.1 which fix the problem ;) !
