### ISSUE TITLE
Allow sending messages with `user_ref` recipient

### ISSUE THREAD

**Issue by matusmarcin** [ker0x/messenger#145]
**Description**  
I am trying to send a message with a `user_ref` string (received from [Messenger Checkbox](https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin/)), this is not possible though, because the constructed message has pretty much hardcoded `recipient` with `id` key.

**Example**  

It could be perhaps done just by removing type `string` for $recipient from [message on Send](https://github.com/ker0x/messenger/blob/bb0f5a0a273c1fe834b70ad1a3be7fbddec7a63a/src/Api/Send.php#L24) and `?string` type in [the constructor of SendRequest](https://github.com/ker0x/messenger/blob/bb0f5a0a273c1fe834b70ad1a3be7fbddec7a63a/src/Request/SendRequest.php#L58).

Then the following should work:

`$messenger->send()->message(['user_ref' => $recipient], $message);`

And the constructed message would comply with the format specified [here](https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin/#6--send-a-message-with-user-ref).

```
{
  "recipient": {
    "user_ref":"<UNIQUE_REF_PARAM>"
  }, 
  "message": {
    "text":"hello, world!"
  }
```

**Comment by ker0x** [comment]
Hello @matusmarcin, thank you for reporting this issue. I just release a patch to fix it. You can now pass a string or an array as recipient.

**Comment by matusmarcin** [comment]
Wow, @ker0x, that's amazing. Thanks a lot!

I am going to try it out.

**Comment by matusmarcin** [comment]
@ker0x Confirming that it works for me. Thank you for a quick fix.
