### ISSUE TITLE
3.4.1 release?

### ISSUE THREAD

**Issue by caleuanhopkins** [ker0x/messenger#159]
Can see from: https://github.com/ker0x/messenger/commit/cf773c193164d218382c1a1ca1c3b59cab9d7b1a Guzzle has been bumped to v7. Packagist defaults to 3.4 release which only has Guzzle 6.2 and causes compatibility issues. Are we able to get an updated release with these library bumps, please?

**Comment by ker0x** [comment]
Hello @caleuanhopkins, I will work on a new release during the current week!

**Comment by caleuanhopkins** [comment]
awesome! for now we're pulling `dev-master` from packagist whilst we're working locally but obviously our concern was pushing to production using that development branch 👍

**Comment by ker0x** [comment]
@caleuanhopkins version `3.5.0` is now available 😉
